version: 2

updates:
  # C#/.NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    ignore:
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Bcl.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Moq"
        update-types: ["version-update:semver-major"]
    labels:
      - ".NET"
      - "dependencies"
      - "nuget"
      - "automated-update"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

  # JavaScript/Node (npm) for sample apps
  - package-ecosystem: "npm"
    directory: "/samples/apps"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    labels:
      - "npm"
      - "dependencies"
      - "automated-update"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/python/"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    labels:
      - "python"
      - "dependencies"
      - "automated-update"
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

  # Java (Maven)
  - package-ecosystem: "maven"
    directory: "/samples/java/"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    labels:
      - "java"
      - "dependencies"
      - "automated-update"
    groups:
      java-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    labels:
      - "github-actions"
      - "dependencies"
      - "automated-update"
    groups:
      actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

  # Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Bryan-Roe
    reviewers:
      - Bryan-Roe
    labels:
      - "devcontainers"
      - "dependencies"
      - "automated-update"
    groups:
      devcontainers-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Dependabot]"

# Enable security updates for all package ecosystems (explicit)
enable-beta-ecosystems: true

# Uncomment and configure below for private registries if needed
# registries:
#   - type: npm-registry
#     url: https://registry.example.com
#     token: ${{ secrets.NPM_TOKEN }}

# Automerge (uncomment if desired and safe for your workflow)
# automerge: true
