version: 2

updates:
  # C#/.NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Bcl.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Moq"
        update-types: ["version-update:semver-major"]
    labels:
      - ".NET"
      - "dependencies"
      - "nuget"
      - "automated-update"
    groups:
      # Group all NuGet updates into a single PR per run
      dotnet-dependencies:
        patterns:
          - "*"

  # JavaScript/Node (npm) for sample apps
  - package-ecosystem: "npm"
    directory: "/samples/apps"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "npm"
      - "dependencies"
      - "automated-update"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/python/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "python"
      - "dependencies"
      - "automated-update"
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Java (Maven)
  - package-ecosystem: "maven"
    directory: "/samples/java/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "java"
      - "dependencies"
      - "automated-update"
    groups:
      java-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated-update"
    groups:
      actions-dependencies:
        patterns:
          - "*"

  # Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "devcontainers"
      - "dependencies"
      - "automated-update"
    groups:
      devcontainers-dependencies:
        patterns:
          - "*"

# General options
# Limit the number of open PRs to reduce noise
open-pull-requests-limit: 10

# Enable security updates for all package ecosystems
# (Dependabot does this by default, but this is explicit)
# See: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates
