version: 2
updates:
  # Consolidated nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Bcl.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Moq"
        update-types: ["version-update:semver-major"]
    labels:
      - ".NET"
      - "dependencies"
      - "nuget"
      - "automated-update"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/samples/apps"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "npm"
      - "dependencies"
      - "automated-update"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/python/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "python"
      - "dependencies"
      - "automated-update"

  # Maintain dependencies for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated-update"

  # Maintain dependencies for devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "devcontainers"
      - "dependencies"
      - "automated-update"
