version: "3.8"

# Development overrides for Docker Compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  ai-workspace:
    build:
      target: runtime
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Development volume mounts for hot reloading
      - ./01-notebooks:/app/01-notebooks
      - ./02-agents:/app/02-agents
      - ./03-models-training:/app/03-models-training
      - ./04-plugins:/app/04-plugins
      - ./05-samples-demos:/app/05-samples-demos
      - ./06-backend-services:/app/06-backend-services
      - ./scripts:/app/scripts
      - ./docker:/app/docker
      # Keep data volumes
      - ai_data:/app/data
      - ai_models:/app/models
      - ai_uploads:/app/uploads
      - ai_logs:/app/logs
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  # Development database for testing
  postgres:
    image: postgres:15-alpine
    container_name: ai-workspace-postgres-dev
    environment:
      - POSTGRES_DB=ai_workspace
      - POSTGRES_USER=aiuser
      - POSTGRES_PASSWORD=devpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - ai-network

volumes:
  postgres_dev_data:
    driver: local
