name: Reusable Deploy
on:
  workflow_call:
    inputs:
      registry: {required: false, type: string}
      image_name: {required: false, type: string, default: my-app}
      tag: {required: false, type: string, default: latest}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: {}
      GITHUB_TOKEN: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        if: inputs.registry != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ${{ inputs.registry && inputs.registry + '/' || '' }}${{ inputs.image_name }}:${{ inputs.tag }} .
          docker push ${{ inputs.registry && inputs.registry + '/' || '' }}${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.image_name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ inputs.registry && inputs.registry + '/' || '' }}${{ inputs.image_name }}:${{ inputs.tag }}
