name: Reusable Tests
on:
  workflow_call:
    inputs:
      dotnet: {required: false, type: boolean, default: false}
      python: {required: false, type: boolean, default: false}
      node: {required: false, type: boolean, default: false}
    secrets: inherit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        if: inputs.dotnet == true
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Run .NET tests
        if: inputs.dotnet == true
        run: dotnet test 01-core-implementations/dotnet/SK-dotnet.sln --configuration Release --no-build

      - name: Setup Python
        if: inputs.python == true
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        if: inputs.python == true
        run: |
          cd 01-core-implementations/python
          pip install -r requirements.txt
      - name: Run Python tests
        if: inputs.python == true
        run: |
          cd 01-core-implementations/python
          pytest -q tests

      - name: Setup Node
        if: inputs.node == true
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Node dependencies
        if: inputs.node == true
        run: |
          cd 01-core-implementations/typescript
          npm ci
      - name: Run Node tests
        if: inputs.node == true
        run: |
          cd 01-core-implementations/typescript
          npm test --if-present
