# https://circleci.com/docs/2.0/config-intro/

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - run: echo "Running tests using Node.js and browsers"
      - run: npm install
      - run: npm test

  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run deploy
      - run: echo "Running error fixing job"
      - run: ./fix-errors.sh

  fix-errors:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: echo "Fixing errors within the docker container"
      - run: ./fix-errors.sh

workflows:
  test-flow:
    jobs:
      - test
      - build
      - deploy
