# https://circleci.com/docs/2.0/config-intro/

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.0.0-browsers
    steps:
      - checkout
      - run: echo "Running tests using Node.js and browsers"
      - run: npm install
      - run: npm test
      - run: echo "Running tests for .NET project"
      - run: dotnet restore
      - run: dotnet build
      - run: ./fix-errors.sh
      - run: dotnet test --no-build --verbosity normal
      - run: echo "Verifying installations of dependencies..."
      - run: pip list
      - run: dotnet --list-sdks
      - run: sudo apt-get update && sudo apt-get install -y systemd
      - run: echo "Cleaning up temporary files and directories"
      - run: sudo rm -rf /tmp/*
      - run: echo "Pruning Docker system"
      - run: docker system prune -f
      - run: echo "Verifying available disk space"
      - run: df -h

  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: echo "Building .NET project"
      - run: dotnet build --no-restore
      - run: ./fix-errors.sh
      - run: echo "Verifying installations of dependencies..."
      - run: pip list
      - run: dotnet --list-sdks
      - run: sudo apt-get update && sudo apt-get install -y systemd
      - run: echo "Cleaning up temporary files and directories"
      - run: sudo rm -rf /tmp/*
      - run: echo "Pruning Docker system"
      - run: docker system prune -f
      - run: echo "Verifying available disk space"
      - run: df -h

  deploy:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm run deploy
      - run: echo "Deploying .NET project"
      - run: dotnet publish --no-restore
      - run: ./fix-errors.sh
      - run: echo "Verifying installations of dependencies..."
      - run: pip list
      - run: dotnet --list-sdks
      - run: sudo apt-get update && sudo apt-get install -y systemd
      - run: echo "Cleaning up temporary files and directories"
      - run: sudo rm -rf /tmp/*
      - run: echo "Pruning Docker system"
      - run: docker system prune -f
      - run: echo "Verifying available disk space"
      - run: df -h

  verify-codespace-startup:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: ./fix-codespace-startup.sh
      - run: echo "Verifying installations of dependencies..."
      - run: pip list
      - run: dotnet --list-sdks
      - run: echo "Cleaning up temporary files and directories"
      - run: sudo rm -rf /tmp/*
      - run: echo "Pruning Docker system"
      - run: docker system prune -f
      - run: echo "Verifying available disk space"
      - run: df -h

  run-api-server:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: echo "Cleaning up temporary files and directories"
      - run: sudo rm -rf /tmp/*
      - run: echo "Pruning Docker system"
      - run: docker system prune -f
      - run: echo "Verifying available disk space"
      - run: df -h

workflows:
  test-flow:
    jobs:
      - test
      - build
      - deploy
      - verify-codespace-startup
      - run-api-server
