# https://circleci.com/docs/2.0/config-intro/

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - run: echo "Running tests using Node.js and browsers"
      - run: npm install
      - run: npm test
      - run: echo "Running tests for .NET project"
      - run: dotnet restore
      - run: dotnet test --no-build --verbosity normal

  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: echo "Building .NET project"
      - run: dotnet build --no-restore

  deploy:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run deploy
      - run: echo "Deploying .NET project"
      - run: dotnet publish --no-restore

workflows:
  test-flow:
    jobs:
      - test
      - build
      - deploy
