name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GNAT toolchain
        run: >
          sudo apt-get update &&
          sudo apt-get install gnat gprbuild

      - name: Build
        run: gprbuild -j0 -p

      - name: Trigger Ensure Success Workflow
        run: |
          gh workflow run ensure-success.yml
