name: Java CI/CD

on:
  push:
    branches: [main, develop, "feature/*", "release/*"]
    paths:
      - "java/**"
      - ".github/workflows/ci-java.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "java/**"
      - ".github/workflows/ci-java.yml"
  workflow_dispatch:

env:
  JAVA_VERSION: "11"

jobs:
  # Build and test Java projects
  build-and-test:
    name: Build & Test Java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: |
          if [ -f "java/gradlew" ]; then
            chmod +x java/gradlew
          fi

      - name: Build with Gradle
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew build
          else
            gradle build
          fi

      - name: Run tests
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew test
          else
            gradle test
          fi

      - name: Generate test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-java-${{ matrix.java-version }}
          path: java/build/reports/tests/test/

      - name: Code Coverage
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew jacocoTestReport
          else
            gradle jacocoTestReport
          fi

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: matrix.java-version == '11'
        with:
          file: java/build/reports/jacoco/test/jacocoTestReport.xml
          flags: java
          name: java-coverage

  # Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: OWASP Dependency Check
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew dependencyCheckAnalyze
          fi

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-report
          path: java/build/reports/

  # Package and publish
  package:
    name: Package Java
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Build JAR
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew jar
          else
            gradle jar
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: java/build/libs/*.jar

      - name: Publish to Maven Central (on release)
        if: startsWith(github.ref, 'refs/tags/java-')
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd java
          if [ -f "gradlew" ]; then
            ./gradlew publish
          else
            gradle publish
          fi
