# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build and Test Dlang Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Set up Dlang
      uses: dlang-community/setup-dlang@v1 # Use a version tag for clarity

    - name: Cache Dlang dependencies
      uses: actions/cache@v4
      with:
        path: ~/.dub
        key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
        restore-keys: |
          ${{ runner.os }}-dub-

    - name: Build & Test
      env:
        DC: ldc2 # Define the compiler explicitly
      run: |
        dub build --compiler=$DC
        dub test --compiler=$DC
