# Workflow to trigger Datadog Synthetic tests within your Datadog organization
# For more information, see: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

name: Run Datadog Synthetic tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  # Optimize trigger to only run for changes in specific paths
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Use a matrix to run the tests across multiple environments
    strategy:
      matrix:
        environment: [staging, production]
        include:
          - environment: staging
          - environment: production

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Datadog Synthetic tests
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v1.0.0 # Pin the action to a specific version
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          test_search_query: 'tag:e2e-tests' # Modify this tag to suit your tagging strategy
        env:
          ENVIRONMENT: ${{ matrix.environment }}

      # Step 3: Notify on failure
      - name: Notify on Failure
        if: failure()
        run: echo "Datadog Synthetic tests failed in ${{ matrix.environment }} environment"
