name: "Microsoft Defender For DevOps"

on:
  push:
    branches: [ "${{ github.ref_name }}" ] # Dynamic branch name
  pull_request:
    branches: [ "${{ github.ref_name }}" ] # Dynamic branch name
  schedule:
    - cron: '38 5 * * 5' # Weekly scan every Friday at 5:38 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  MSDO:
    runs-on: windows-latest # 'windows-latest' is currently supported
    timeout-minutes: 30
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # Added cross-platform testing
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache NuGet packages
      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Step 3: Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x

      # Step 4: Run Microsoft Security DevOps
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v2.0.1 # Pinned to a specific version
        id: msdo

      # Step 5: Validate SARIF file
      - name: Validate SARIF file
        if: ${{ steps.msdo.outputs.sarifFile != '' && steps.msdo.outputs.sarifFile != null }}
        run: |
          echo "SARIF file exists and is valid."
          # Optionally add additional validation logic here

      # Step 6: Upload results to Security tab
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

  # Optional: Add support for testing on Ubuntu
  MSDO_Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet: [5.0.x, 6.0.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v2.0.1 # Pinned to a specific version
        id: msdo

      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
