name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 11 * * 0'
  workflow_dispatch:

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: \'npm\'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Fix Errors
        run: |
          chmod +x ./fix-errors.sh
          ./fix-errors.sh

      - name: Upload Analysis Results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Run npm audit with fail on high severity
        run: npm audit --audit-level=high

      - name: Install systemd
        run: sudo apt-get update && sudo apt-get install -y systemd

      - name: Start systemd
        run: sudo systemctl start systemd

      - name: Verify systemd status
        run: sudo systemctl status systemd

      - name: Run fix-errors.sh
        run: |
          chmod +x ./fix-errors.sh
          ./fix-errors.sh

      - name: Log Error Message
        if: failure()
        run: echo "Error occurred during the ESLint scanning process"
