name: lintr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 19 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@<commit-sha> # Pin SHA for security

      - name: Setup R
        uses: r-lib/actions/setup-r@<commit-sha> # Pin SHA for security

      - name: Setup lintr
        uses: r-lib/actions/setup-r-dependencies@<commit-sha> # Pin SHA for security
        with:
          extra-packages: lintr

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@<commit-sha> # Pin SHA for security
        with:
          sarif_file: lintr-results.sarif
