name: "Mayhem for API"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * 0' # Run weekly at 3 AM UTC
  workflow_dispatch:

jobs:
  mayhem-for-api:
    name: Mayhem for API
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start your API
        run: ./run_your_api.sh &

      - name: Check API Health
        run: |
          sleep 10
          curl -f ${{ secrets.API_URL }}/health || exit 1

      - name: Mayhem for API
        uses: ForAllSecure/mapi-action@193b709971cc377675e33284aecbf9229853e010
        with:
          mapi-token: ${{ secrets.MAPI_TOKEN }}
          api-url: ${{ secrets.API_URL }}
          api-spec: ${{ secrets.API_SPEC_URL }}
          duration: 120
          sarif-report: mapi.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: mapi.sarif

      - name: Stop API
        run: pkill -f run_your_api.sh
