# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# NowSecure: The Mobile Security Experts <https://www.nowsecure.com/>.
#
# To use this workflow, you must be an existing NowSecure customer.
# If you are not an existing customer, click here:
# <https://info.nowsecure.com/github-request>.
#
# Instructions:
#
# 1. In the settings for your repository, click "Secrets" and
#    paste in your Platform token. If you do not have a token,
#    log in to the NowSecure Platform and go to "Profile & Preferences"
#    then generate a token.
#
# 2. Follow the annotated workflow below and make any necessary updates.
#    Run the workflow and review the "Security" tab once the action has completed.

name: "NowSecure"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  nowsecure:
    name: NowSecure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build your application
      run: ./gradlew assembleDebug # Update this to build your Android application

    - name: Run NowSecure
      uses: nowsecure/nowsecure-action@3b439db31b6dce857b09f5222fd13ffc3159ad26
      with:
        token: ${{ secrets.NS_TOKEN }}
        app_file: app-debug.apk # Update this to the path of your app file
        group_id: your-group-id # Update this to your desired group ID

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: path/to/your.sarif # Update this to the path of your SARIF file
