# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Pyre with GitHub's
# Code Scanning feature.
#
# Pyre is a performant type checker for Python compliant with
# PEP 484. Pyre can analyze codebases with millions of lines
# of code incrementally – providing instantaneous feedback
# to developers as they write code.
#
# See https://pyre-check.org

name: Pyre

on:
  # Workflow can be manually triggered
  workflow_dispatch:
  # Trigger on pushes and pull requests affecting Python files
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'

permissions:
  contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write  # Required for Code Scanning integration
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are checked out

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Specify the Python version
          cache: \'pip\'

      # Cache Python dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Validate requirements file
      - name: Validate requirements file
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt not found!"
            exit 1
          fi

      # Run Pyre type checker
      - name: Run Pyre
        uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d
        with:
          # Documentation: https://github.com/facebook/pyre-action#inputs
          repo-directory: './'
          requirements-path: 'requirements.txt'

      # Upload Pyre results
      - name: Upload Pyre results
        uses: actions/upload-artifact@v4
        with:
          name: pyre-results
          path: ./pyre-results/

      # Annotate pull requests with Pyre findings
      - name: Annotate PR with Pyre results
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Annotating the pull request with Pyre results"
