name: Remove Binary Artifacts

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  remove-binary-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and delete binary artifact files
        run: |
          find . -type f -name '__azurite_db_blob__.json' -delete
          find . -type f -name '__azurite_db_blob_extent__.json' -delete
          find . -type f -name '__azurite_db_queue__.json' -delete
          find internal-semantic-core -type f -name '__azurite_db_blob__.json' -delete
          find internal-semantic-core -type f -name '__azurite_db_blob_extent__.json' -delete
          find internal-semantic-core -type f -name '__azurite_db_queue__.json' -delete
          find internal-semantic-core -type f -name '__azurite_db_queue_extent__.json' -delete
          find internal-semantic-core -type f -name '__azurite_db_table__.json' -delete
          find . -type f -name '*.bin' -delete
          find . -type f -name '*.exe' -delete
          find . -type f -name '*.dll' -delete
          find . -type f -name '*.zip' -delete
          find . -type f -name '*.json' -delete

      - name: Upload report of deleted files
        uses: actions/upload-artifact@v3
        with:
          name: deleted-files-report
          path: deleted-files-report.txt

      - name: Generate report of deleted files
        run: |
          echo "Deleted files:" > deleted-files-report.txt
          find . -type f -name '__azurite_db_blob__.json' -print >> deleted-files-report.txt
          find . -type f -name '__azurite_db_blob_extent__.json' -print >> deleted-files-report.txt
          find . -type f -name '__azurite_db_queue__.json' -print >> deleted-files-report.txt
          find internal-semantic-core -type f -name '__azurite_db_blob__.json' -print >> deleted-files-report.txt
          find internal-semantic-core -type f -name '__azurite_db_blob_extent__.json' -print >> deleted-files-report.txt
          find internal-semantic-core -type f -name '__azurite_db_queue__.json' -print >> deleted-files-report.txt
          find internal-semantic-core -type f -name '__azurite_db_queue_extent__.json' -print >> deleted-files-report.txt
          find internal-semantic-core -type f -name '__azurite_db_table__.json' -print >> deleted-files-report.txt
          find . -type f -name '*.bin' -print >> deleted-files-report.txt
          find . -type f -name '*.exe' -print >> deleted-files-report.txt
          find . -type f -name '*.dll' -print >> deleted-files-report.txt
          find . -type f -name '*.zip' -print >> deleted-files-report.txt
          find . -type f -name '*.json' -print >> deleted-files-report.txt

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: deleted-files-report.txt
