# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '41 2 * * *'
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Stale
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'

    - name: Set up Docker for containerized deployment
      run: |
        echo "Setting up Docker..."
        docker build -t stale-job .
        docker run -d -p 80:80 stale-job

    - name: Verify installations of dependencies
      run: |
        echo "Verifying installations of dependencies..."
        # Add your verification commands here
        npm list
        pip list
        dotnet --list-sdks

    - name: Run the API server
      run: |
        echo "Running the API server..."
        # Add your commands to run the API server here
        npm start
