#!/usr/bin/env python3
"""
Bedrock Agent Event Type module

Copyright (c) 2025 Bryan Roe
Licensed under the MIT License

This file is part of the Semantic Kernel - Advanced AI Development Framework.
Original work by Bryan Roe.

Author: Bryan Roe
Created: 2025
License: MIT
"""

# Copyright (c) Microsoft. All rights reserved.

from enum import Enum

from semantic_kernel.utils.feature_stage_decorator import experimental


@experimental
class BedrockAgentEventType(str, Enum):
    """Bedrock Agent Event Type."""

    # Contains the text response from the agent.
    CHUNK = "chunk"
    # Contains the trace information (reasoning process) from the agent.
    TRACE = "trace"
    # Contains the function call requests from the agent.
    RETURN_CONTROL = "returnControl"
    # Contains the files generated by the agent using the code interpreter.
    FILES = "files"
