name: Auto Generate Issues

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  issues: write

jobs:
  generate-issues:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 3: Install Node.js dependencies
      - name: Install dependencies
        run: npm ci # Use `npm ci` for faster, reliable installs in CI/CD

      # Step 4: Generate issues
      - name: Generate issues
        env:
          PYTHONPATH: scripts # Added environment variable for Python scripts
        run: |
          echo "Generating issues based on predefined criteria and templates..."
          python scripts/generate_issues.py

      # Step 5: Fix errors (if any)
      - name: Fix Errors
        if: failure()
        run: ./fix-errors.sh

      # Step 6: Log error message if fix-errors.sh fails
      - name: Log Error Message
        if: failure()
        run: echo "Error occurred during the issue generation process"

      # Step 7: Ensure best practices adherence
      - name: Ensure best practices adherence
        run: |
          echo "Ensuring generated issues adhere to best practices..."
          python scripts/check_best_practices.py

      # Step 8: Notify trusted people for approval
      - name: Notify trusted people for approval
        run: |
          echo "Notifying trusted people for approval..."
          python scripts/notify_approvers.py

      # Step 9: Enhanced logging and monitoring
      - name: Enhanced Logging and Monitoring
        run: |
          echo "Setting up enhanced logging and monitoring..."
          python scripts/setup_logging.py

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, node]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup environment and run language-specific linting
      - name: Setup ${{ matrix.language }}
        run: |
          case "${{ matrix.language }}" in
            python)
              python -m pip install --upgrade pip
              pip install flake8
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
              ;;
            node)
              npm ci # Enforce `npm ci` for consistent installs
              npm run lint
              ;;
          esac
