name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
      continue-on-error: false
    - name: make
      run: make
      continue-on-error: false
    - name: make check
      run: make check
      continue-on-error: false
    - name: make distcheck
      run: make distcheck
      continue-on-error: false
