# Workflow to scan project vulnerabilities using CRDA

name: CRDA Scan

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: "0 3 * * 0" # Run weekly on Sunday at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write # Required for uploading SARIF results

jobs:
  crda-scan:
    name: Scan project vulnerabilities with CRDA
    runs-on: ubuntu-20.04
    permissions:
      contents: read            # For actions/checkout to fetch code
      security-events: write    # For redhat-actions/crda to upload SARIF results

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Validate secrets
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.CRDA_KEY }}" ] && [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "Either CRDA_KEY or SNYK_TOKEN must be set"
            exit 1
          fi

      # Step 3: Set up programming environments (matrix strategy for parallel installation)
      - name: Set up programming environments
        strategy:
          matrix:
            language: [node, python, java]
        uses: actions/setup-${{ matrix.language }}@v4
        with:
          node-version: ${{ matrix.language == 'node' && '18' || '' }}
          python-version: ${{ matrix.language == 'python' && '3.11' || '' }}
          java-version: ${{ matrix.language == 'java' && '11' || '' }}

      # Step 4: Install CRDA CLI
      - name: Install CRDA CLI
        uses: redhat-actions/openshift-tools-installer@v2
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      # Step 5: Run CRDA scan
      - name: CRDA Scan
        id: scan
        uses: redhat-actions/crda@v2
        with:
          crda_key: ${{ secrets.CRDA_KEY }}           # Either use crda_key or snyk_token
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          upload_artifact: true

      # Step 6: Upload SARIF results as an artifact
      - name: Upload SARIF Results
        uses: actions/upload-artifact@v4
        with:
          name: crda-scan-results
          path: results.sarif
