#
# This workflow runs the dotnet formatter on all c-sharp code.
#

name: dotnet format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-format:
<<<<<<< HEAD
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
=======
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "8.0", configuration: Release, os: ubuntu-latest }
          - { dotnet: "9.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    env:
      NUGET_CERT_REVOCATION_MODE: offline

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
>>>>>>> 6829cc1483570aacfbb75d1065c9f2de96c1d77e

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dotnet tools
      run: dotnet tool restore
      
    - name: Check format
      run: dotnet format --verify-no-changes --verbosity detailed
      
    - name: Fail if files are not formatted
      if: ${{ failure() }}
      run: |
        echo "Some files are not formatted correctly. Run 'dotnet format' to fix."
        exit 1

    - name: Install systemd
      run: sudo apt-get update && sudo apt-get install -y systemd

    - name: Start systemd
      run: sudo systemctl start systemd

    - name: Verify systemd status
      run: sudo systemctl status systemd
