# Frogbot Scan Pull Request Workflow
#
# This workflow automatically scans new pull requests for security vulnerabilities
# using JFrog Xray via Frogbot. See: https://github.com/jfrog/frogbot#frogbot

name: "Frogbot Scan Pull Request"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write # Minimize permissions if possible

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot

    steps:
      # Step 1: Checkout Pull Request Code
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Step 2: Validate Required Secrets
      - name: Validate Required Secrets
        run: |
          if [[ -z "${{ secrets.JF_URL }}" || -z "${{ secrets.JF_ACCESS_TOKEN }}" ]]; then
            echo "Missing JFrog secrets (JF_URL, JF_ACCESS_TOKEN)."
            exit 1
          fi

      # Step 3: Cache JFrog Data (Improves build speed)
      - name: Cache JFrog Directory
        uses: actions/cache@v3
        with:
          path: ~/.jfrog
          key: ${{ runner.os }}-frogbot-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-frogbot-

      # Step 4: Run Frogbot Security Scan
      - name: Frogbot Security Scan
        uses: jfrog/frogbot@v2.10.0
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment if your project requires dependency installation
          # JF_INSTALL_DEPS_CMD: "npm install"
          # JF_DEPS_REPO: ""
          # JF_RELEASES_REPO: ""

      # Step 5: Unified Error Handling
      - name: Handle Frogbot Failures
        if: failure()
        run: echo "Frogbot scan failed. Please check the logs above for details."
