name: "Frogbot Scan and Fix"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.JF_URL }}" ] || [ -z "${{ secrets.JF_ACCESS_TOKEN }}" ]; then
            echo "Required secrets are missing. Exiting."
            exit 1
          fi

      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.jfrog
          key: ${{ runner.os }}-jfrog-cache
          restore-keys: |
            ${{ runner.os }}-jfrog-cache

      - name: Frogbot Scan and Fix
        uses: jfrog/frogbot@8fbeca612957ae5f5f0c03a19cb6e59e237026f3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint workflow
        uses: rhysd/actionlint@v1

      - name: Install systemd
        run: sudo apt-get update && sudo apt-get install -y systemd

      - name: Start systemd
        run: sudo systemctl start systemd

      - name: Verify systemd status
        run: sudo systemctl status systemd

      - name: Fix Errors
        if: failure()
        run: ./fix-errors.sh

      - name: Log Error Message
        if: failure()
        run: echo "Error occurred during the Frogbot scan and fix process"
