name: Handle Not Found Error

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  handle-not-found-error:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for Not Found Error
        run: |
          if grep -q "Not Found - https://docs.github.com/rest/repos/contents#get-repository-content" $GITHUB_EVENT_PATH; then
            echo "Error found: Not Found - https://docs.github.com/rest/repos/contents#get-repository-content"
            exit 1
          else
            echo "No Not Found error found."
          fi
