# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration. For more information, see:
# https://github.com/actions/labeler

name: Labeler

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  apply-labels:
    name: Apply Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3.1.0  # Specify the exact version

      # Apply labels based on labeler configuration
      - name: Apply labeler
        uses: actions/labeler@v4.1.2  # Specify the exact version
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      # Add a step to handle potential errors
      - name: Error handling
        if: failure()
        run: echo "An error occurred while applying labels. Please check the logs for more details."

      # Add a step to notify on failure (optional)
      - name: Notify failure
        if: failure()
        run: |
          echo "Sending notification about the failure"
          # Example: Send a Slack notification (requires setup)
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Labeler workflow failed"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    timeout-minutes: 10  # Add a timeout to prevent running indefinitely
