name: Label pull request

on: [pull_request_target]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GH_ACTIONS_PR_WRITE }}"

      - name: Error handling
        if: failure()
        run: |
          echo "An error occurred while applying labels"
          # Optionally create an issue to track the failure
          gh issue create --title "Labeling failed on PR" --body "Labeling failed on PR #${{ github.event.pull_request.number }}"

      - name: Notify on Slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Labeling failed on PR #${{ github.event.pull_request.number }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Labeling succeeded on PR #${{ github.event.pull_request.number }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
