name: Label pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Labeler Configuration
        run: |
          if [[ ! -f .github/labeler.yml ]]; then
            echo "Labeler configuration file is missing!"
            exit 1
          fi
          yamllint .github/labeler.yml # Ensure the file is valid

      - name: Apply labels using Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ env.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      - name: Handle Errors
        if: failure()
        run: |
          echo "An error occurred while applying labels"
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Labeler workflow failed for PR #${{ github.event.pull_request.number }}."}' \
            ${{ env.SLACK_WEBHOOK }}

      - name: Notify Success
        if: success()
        run: |
          echo "Labels successfully applied to PR #${{ github.event.pull_request.number }}"
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Labels successfully applied to PR #${{ github.event.pull_request.number }}."}' \
            ${{ env.SLACK_WEBHOOK }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.gem
          key: ${{ runner.os }}-gem-cache
          restore-keys: |
            ${{ runner.os }}-gem-cache

      - name: Install and Run YAML Linter
        run: |
          gem install yamllint
          yamllint .github/workflows
          yamllint .github/labeler.yml # Lint additional YAML files
