# This workflow will triage pull requests and apply a label based on the paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml file with configuration. For more information, see:
# https://github.com/actions/labeler

name: Label pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      - name: Error handling
        if: failure()
        run: |
          echo "An error occurred while applying labels"
          # Add additional error handling or logging here
          # For example, send a notification to Slack
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Labeler workflow failed for PR #${{ github.event.pull_request.number }}."}' ${{ secrets.SLACK_WEBHOOK_URL }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint YAML
        run: |
          gem install yamllint
          yamllint .github/workflows/label-pr.yml
