# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration. For more information, see:
# https://github.com/actions/labeler

name: Labeler

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Apply Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    # Step to checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Step to apply labels based on the configuration in .github/labeler.yml
    - name: Apply Labeler
      uses: actions/labeler@v4.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    # Optional: Step to handle errors
    - name: Notify on failure
      if: failure()
      run: echo "Label application failed"
