name: Node PR Lint, Build and Test

on:
  # Trigger when manually run
  workflow_dispatch:

  # Trigger on pushes to `main` or `rel/*`
  push:
    branches:
      - main
      - rel/*

  # Trigger on pull requests to `main` or `rel/*`
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  Build:
    # Use template from https://github.com/microsoft/vscode-azuretools/tree/main/.github/workflows
    uses: microsoft/vscode-azuretools/.github/workflows/jobs.yml@main
    
  DownloadArtifact:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: my-artifact
        path: ./artifacts
        merge-multiple: false
