name: Dependency Vulnerability Monitor

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  dependency-vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependency Vulnerability Scan
        uses: github/dependency-review-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: 'java,python,csharp,cpp,javascript'
        id: init-codeql

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:dependency-vulnerability-scan'

      - name: Notify Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Dependency vulnerabilities detected in repository.'
