name: Dependency Vulnerability Monitor

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  dependency-vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Dependency Vulnerability Scan using Dependabot
      - name: Run Dependency Vulnerability Scan
        uses: dependabot/dependabot-core@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Create issues for new vulnerabilities
      - name: Create issues for new vulnerabilities
        uses: actions/github-script@v6
        with:
          script: |
            const { data: vulnerabilities } = await github.dependency_graph.getVulnerabilities({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const vulnerability of vulnerabilities) {
              await github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `New vulnerability found: ${vulnerability.package_name}`,
                body: `A new vulnerability has been found in the package ${vulnerability.package_name}. Please review and address it.`,
                labels: ['security', 'vulnerability'],
              });
            }
