# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at 00:00 UTC
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Test on multiple OS
        node-version: [18.x, 20.x, 22.x] # Supported Node.js versions
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4 # Pin action version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          npm-shrinkwrap.json # Ensure cache efficiency

    - name: Install dependencies
      run: npm ci
      shell: bash # Explicitly specify shell

    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Build project
      run: npm run build --if-present
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash

    - name: Upload build artifacts
      if: success() # Only upload if the build and tests succeed
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/

    - name: Report test coverage
      run: |
        if [ -n "${{ secrets.CODECOV_TOKEN }}" ]; then
          npx codecov -t ${{ secrets.CODECOV_TOKEN }}
        else
          echo "Codecov token not found. Skipping coverage report."
        fi
      shell: bash

    - name: Notify success
      if: success()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-message: "Build succeeded for ${{ github.repository }} on branch ${{ github.ref_name }}."
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify failure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-message: "Build failed for ${{ github.repository }} on branch ${{ github.ref_name }}."
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

    - name: Cleanup
      run: rm -rf ./temp
      shell: bash
