name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v4

    # Step 2: Cache Node.js modules
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Step 3: Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 4: Clean Build Directory
    - name: Clean Build Directory
      run: rm -rf ./build

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: npm ci # Faster and more consistent than npm install

    # Step 6: Format Code
    - name: Format Code
      run: npm run format
      continue-on-error: true # Allows workflow to proceed even if formatting fails

    # Step 7: Run Linter
    - name: Run Linter
      run: npm run lint

    # Step 8: Run Security Audit
    - name: Run Security Audit
      run: npm audit --production

    # Step 9: Run Tests
    - name: Run Tests
      run: npm test

    # Step 10: Build
    - name: Build
      run: gulp

    # Step 11: Run npm start command
    - name: Run Application
      run: npm start

    # Step 12: Upload Build Artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build
        retention-days: 30 # Optional: Customize retention period for artifacts
