# This workflow uses third-party actions that are not certified by GitHub.
# Review their terms of service, privacy policy, and documentation before use.
# Workflow: Runs PHPMD to analyze PHP code for potential issues.

name: PHPMD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '29 21 * * 5' # Runs every Friday at 21:29 UTC. Adjust as needed.

permissions:
  contents: read # Required for checking out code
  security-events: write # Enables SARIF result uploads securely

jobs:
  PHPMD:
    name: Run PHPMD scanning
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1] # Test multiple PHP versions for compatibility

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4 # Ensure the latest version is used

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} # Use PHP versions from the matrix
          coverage: none
          tools: phpmd

      # Run PHPMD analysis
      - name: Run PHPMD
        run: phpmd . sarif codesize --reportfile phpmd-results.sarif
        continue-on-error: false # Fail the workflow if PHPMD errors occur

      # Upload analysis results to GitHub
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true

      # Optional: Notify team via Slack or email
      # Uncomment and configure if notifications are needed
      # - name: Notify team
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: 'C01234567'
      #     slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
