name: MCP Automatic Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get PR Diff
        id: diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > pr.diff

      - name: Call MCP server for review
        run: |
          COMMENTS=$(curl -s -X POST http://your-mcp-server-url/review \
            -H "Content-Type: application/json" \
            --data-binary "{\"diff\": \"$(cat pr.diff | jq -Rs .)\"}")
          echo "$COMMENTS" > comments.json

      - name: Post review comments
        run: |
          python scripts/post_comments.py comments.json ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
