name: Python Code Quality Checks
on:
  workflow_dispatch:
  pull_request_target:
    branches: [ "main", "feature*" ]
    paths:
      - 'python/**'

jobs:
  pre-commit:
    if: '!cancelled()'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
<<<<<<< main
          cache-dependency-path: "python/pyproject.toml"
      - name: Install SemanticKernel
        run: cd python && poetry install --no-ansi
      - name: Run lint
        run: cd python && poetry run ruff check .
  black:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "python/pyproject.toml"
      - name: Install SemanticKernel
        run: cd python && poetry install --no-ansi
      - name: Run lint
        run: cd python && poetry run black --check .
=======
      - name: Install dependencies
        run: cd python && poetry install
      - uses: pre-commit/action@v3.0.1
>>>>>>> origin/main-auto-tune
