name: "Rubocop"

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: '33 2 * * 3'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.0, 3.1, 3.2] # Add latest Ruby version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Cache Gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Code Scanning integration
      run: bundle add code-scanning-rubocop --version 0.3.0 --skip-install

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: |
        bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
      continue-on-error: false # Allow RuboCop warnings/errors

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: rubocop.sarif
