# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Scorecard supply-chain security

on:
  # For Branch-Protection check. Only the default branch is supported.
  branch_protection_rule:
    types: [created, edited, deleted]
  # To guarantee Maintained check is occasionally updated.
  schedule:
    - cron: '37 16 * * 0' # Runs every Sunday at 16:37 UTC
  # Trigger on pushes to the main branch.
  push:
    branches: [ "main" ]
  # Trigger on pull requests to validate changes before merging.
  pull_request:
    branches: [ "main" ]

# Declare default permissions as read-only for security.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload results to code-scanning dashboard.
      id-token: write # Needed to publish results and get a badge.
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true # Set to true for public repositories.

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5 # Adjust based on your retention policy.

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: my-image-name
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest
          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest

  verify-dependencies:
    runs-on: ubuntu-latest
    needs: docker-setup
    steps:
      - name: Verify installations of dependencies
        run: |
          echo "Verifying installations of dependencies..."
          npm audit --production
          pip check
          dotnet restore --locked-mode

  run-api:
    runs-on: ubuntu-latest
    needs: verify-dependencies
    steps:
      - name: Run the API server
        run: |
          echo "Running the API server..."

      - name: Verify API server is running
        run: curl -f http://localhost:3000 || exit 1

      - name: Verify installations of dependencies
        run: |
          echo "Verifying installations of dependencies..."
          npm list
          pip list
          dotnet --list-sdks
