# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Sobelow is a security-focused static analysis tool for the Phoenix framework. https://sobelow.io/
#
# To use this workflow, you must have GitHub Advanced Security (GHAS) enabled for your repository.
#
# Instructions:
# 2. Follow the annotated workflow below and make any necessary modifications then save the workflow to your repository
#    and review the "Security" tab once the action has run.
name: Sobelow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 19 * * 2'

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: run-action
        uses: sobelow/action@v1.0.1
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          docker push ghcr.io/${{ github.repository }}/my-image-name:$(date +%s)

  verify-dependencies:
    runs-on: ubuntu-latest
    needs: docker-setup
    steps:
      - name: Verify installations of dependencies
        run: |
          echo "Verifying installations of dependencies..."
          # Add your verification commands here
          npm list
          pip list
          dotnet --list-sdks

  run-api:
    runs-on: ubuntu-latest
    needs: verify-dependencies
    steps:
      - name: Run the API server
        run: |
          echo "Running the API server..."
          # Add your commands to run the API server here
          npm start
